DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS accounts;

CREATE TABLE post (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   user TEXT NOT NULL DEFAULT ANONYMOUS,
   message TEXT NOT NULL
);

CREATE TABLE accounts (
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   username TEXT NOT NULL,
   password INTEGER NOT NULL
);